{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 49,
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "\"Размерность графа\"\n",
    "def from_id_width(id, width):\n",
    "    return (id % width, id // width)\n",
    "\n",
    "\"Определяем граф\"\n",
    "def draw_tile(graph, id, style, width):\n",
    "    r = \".\"\n",
    "    if 'number' in style and id in style['number']: r = \"%d\" % style['number'][id] \"стоимость для каждой вершины\"\n",
    "    if 'point_to' in style and style['point_to'].get(id, None) is not None: \"направление для каждой вершины\"\n",
    "        (x1, y1) = id\n",
    "        (x2, y2) = style['point_to'][id]\n",
    "        if x2 == x1 + 1: r = \">\"\n",
    "        if x2 == x1 - 1: r = \"<\"\n",
    "        if y2 == y1 + 1: r = \"v\"\n",
    "        if y2 == y1 - 1: r = \"^\"\n",
    "    if 'start' in style and id == style['start']: r = \"O\" \"начало\"\n",
    "    if 'goal' in style and id == style['goal']: r = \"X\" \"конец\"\n",
    "    if 'path' in style and id in style['path']: r = \"*\" \"путь\"\n",
    "    if id in graph.walls: r = \"#\" * width \"преграды\"\n",
    "    return r\n",
    "\n",
    "\"Рисуем граф\"\n",
    "def draw_grid(graph, width=2, **style):\n",
    "    for y in range(graph.height):\n",
    "        for x in range(graph.width):\n",
    "            print(\"%%-%ds\" % width % draw_tile(graph, (x, y), style, width), end=\"\")\n",
    "        print()\n",
    "\n",
    "\"Определяем класс сеточных графов\"        \n",
    "class SquareGrid:\n",
    "    def __init__(self, width, height):\n",
    "        self.width = width\n",
    "        self.height = height\n",
    "        self.walls = []\n",
    "   \n",
    "    def in_bounds(self, id):\n",
    "        (x, y) = id\n",
    "        return 0 <= x < self.width and 0 <= y < self.height\n",
    "    \n",
    "    def passable(self, id):\n",
    "        return id not in self.walls\n",
    "    \n",
    "    def neighbors(self, id):\n",
    "        (x, y) = id\n",
    "        results = [(x+1, y), (x, y-1), (x-1, y), (x, y+1)]\n",
    "        if (x + y) % 2 == 0: results.reverse() # aesthetics\n",
    "        results = filter(self.in_bounds, results)\n",
    "        results = filter(self.passable, results)\n",
    "        return results\n",
    "\n",
    "\"Класс графов с весами\"    \n",
    "class GridWithWeights(SquareGrid):\n",
    "    def __init__(self, width, height):\n",
    "        super().__init__(width, height)\n",
    "        self.weights = {}\n",
    "    \"определяем цены, здесь у всех вершин 1\"\n",
    "    def cost(self, from_node, to_node):\n",
    "        return self.weights.get(to_node, 1)\n",
    "\n",
    "\n",
    "import heapq\n",
    "\n",
    "\"Класс очередей с приоритетами\"\n",
    "class PriorityQueue:\n",
    "    def __init__(self):\n",
    "        self.elements = []\n",
    "    \n",
    "    def empty(self):\n",
    "        return len(self.elements) == 0\n",
    "    \n",
    "    def put(self, item, priority):\n",
    "        heapq.heappush(self.elements, (priority, item))\n",
    "    \n",
    "    def get(self):\n",
    "        return heapq.heappop(self.elements)[1]\n",
    "\n",
    "\"Определяем разные эвристики\"\n",
    "def heuristic1(a, b):\n",
    "    (x1, y1) = a\n",
    "    (x2, y2) = b\n",
    "    return abs(x1 - x2) + abs(y1 - y2)\n",
    "\n",
    "def heuristic2(a, b):\n",
    "    (x1, y1) = a\n",
    "    (x2, y2) = b\n",
    "    return max(abs(x1 - x2),abs(y1 - y2))\n",
    "\n",
    "\"Алгоритм А*\"\n",
    "def a_star_search(graph, start, goal, heuristic):\n",
    "    \"счетчик количества пройденных вершин\"\n",
    "    counter = 0\n",
    "    \"очередь с приоритетами\"\n",
    "    frontier = PriorityQueue()\n",
    "    frontier.put(start, 0)\n",
    "    \"кортежи вершин откуда пришли и цены\"\n",
    "    came_from = {}\n",
    "    cost_so_far = {}\n",
    "    came_from[start] = None\n",
    "    cost_so_far[start] = 0\n",
    "    \n",
    "    while not frontier.empty():\n",
    "        current = frontier.get()\n",
    "        \n",
    "        if current == goal:\n",
    "            break\n",
    "      \n",
    "        for next in graph.neighbors(current):\n",
    "            new_cost = cost_so_far[current] + graph.cost(current, next)\n",
    "            if next not in cost_so_far or new_cost < cost_so_far[next]:\n",
    "                cost_so_far[next] = new_cost\n",
    "                priority = new_cost + heuristic(goal, next)\n",
    "                frontier.put(next, priority)\n",
    "                came_from[next] = current\n",
    "                counter += 1\n",
    "    \n",
    "    return came_from, cost_so_far, counter\n",
    "\n",
    "\"Построение пути\"\n",
    "def reconstruct_path(came_from, start, goal):\n",
    "    current = goal\n",
    "    path = [current]\n",
    "    while current != start:\n",
    "        current = came_from[current]\n",
    "        path.append(current)\n",
    "    path.append(start) \n",
    "    path.reverse() \n",
    "    return path"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 50,
   "metadata": {},
   "outputs": [],
   "source": [
    "\"Задаем произвольный граф\"    \n",
    "diagram4 = GridWithWeights(10, 10)\n",
    "\"Его преграды\"\n",
    "diagram4.walls = [(1, 7), (1, 8), (2, 7), (2, 8), (3, 7), (3, 8), (3, 9), (1, 2), (4, 5), (3, 5)]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 54,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "43\n",
      ".  .  .  .  .  .  .  .  .  .  \n",
      ".  .  .  .  .  .  .  .  .  .  \n",
      ".  ###.  .  .  .  .  .  .  .  \n",
      ".  .  .  .  .  .  .  .  .  .  \n",
      ".  O  .  .  .  .  .  .  .  .  \n",
      ".  *  .  ######.  .  .  .  .  \n",
      ".  *  *  *  *  .  .  .  .  .  \n",
      ".  #########*  .  .  .  .  .  \n",
      ".  #########*  *  *  X  .  .  \n",
      ".  .  .  ###.  .  .  .  .  .  \n"
     ]
    }
   ],
   "source": [
    "\"Алгоритм с 1ой эвристикой\"\n",
    "came_from, cost_so_far, counter = a_star_search(diagram4, (1, 4), (7, 8), heuristic1)\n",
    "\"Число обработанных вершин\"\n",
    "print(counter)\n",
    "draw_grid(diagram4, width=3, path=reconstruct_path(came_from, start=(1, 4), goal=(7, 8))[2:-1], start=(1, 4), goal=(7, 8))\n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 53,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "53\n",
      ".  .  .  .  .  .  .  .  .  .  \n",
      ".  .  .  .  .  .  .  .  .  .  \n",
      ".  ###.  .  .  .  .  .  .  .  \n",
      ".  .  .  .  .  .  .  .  .  .  \n",
      ".  O  *  .  .  .  .  .  .  .  \n",
      ".  .  *  ######.  .  .  .  .  \n",
      ".  .  *  *  *  *  .  .  .  .  \n",
      ".  #########.  *  *  .  .  .  \n",
      ".  #########.  .  *  X  .  .  \n",
      ".  .  .  ###.  .  .  .  .  .  \n"
     ]
    }
   ],
   "source": [
    "\"Алгоритм со 2ой эвристикой\"\n",
    "came_from, cost_so_far, counter = a_star_search(diagram4, (1, 4), (7, 8), heuristic2)\n",
    "\"Число обработанных вершин\"\n",
    "print(counter)\n",
    "draw_grid(diagram4, width=3, path=reconstruct_path(came_from, start=(1, 4), goal=(7, 8))[2:-1], start=(1, 4), goal=(7, 8))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
